/// <reference types = "Cypress" />
import HomePage_PO from '../../pages/Homepage_PO'
import BloomexCorporateAccount_PO from '../../pages/BloomexCorporateAccount_PO';

class CorporateAccount{

    checkLinkCLientTestimonials(){
        cy.log('Start Check link CLientTestimonials')
        HomePage_PO.getButtonCorporate().click();
        BloomexCorporateAccount_PO.getLinkReadClientTestimonials().click();
        cy.get('.content_title_inner').should('contain', 'Corporate Testimonials');
        cy.log('End Check link CLientTestimonials')
    }

    checkSendingApplicationFor20CorporateDiscount_withCorrectData(){

        cy.log('Start  check Sending Application For 20CorporateDiscount_withCorrectData');

        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});
        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon').should('have.value', 'YT')

        let randomEmail = Math.random().toString(36).substring(2, 8) + Math.floor(Math.random() * 1000);
        let email = 'autogeneratedemail_' + randomEmail + '@gmail.com'

        BloomexCorporateAccount_PO.getFieldEmail().type(email);
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});
        cy.pause();
        BloomexCorporateAccount_PO.getAlertCorporateApplicationSend()
        .should('contain', 'Thank You - your application for a Bloomex Corporate Account has been received. A dedicated Corporate Account Manager will contact you shortly to introduce themselves, present our product selection, answer any questions you may have and finalize the application process');

        cy.log('End check Sending Application For 20CorporateDiscount_withCorrectData')
        cy.allure().endStep();
    }

    checkSendingApplicationFor20CorporateDiscount_withEmptyFields_EmptyFirstName(){
        cy.log('Start check with All Empty Fields')
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});
        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your first name.');
          })
        cy.log('End check with All Empty Fields')


   cy.log('Start  check Sending Application For 20CorporateDiscount_withEmptyFirstName');

        // BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon').should('have.value', 'YT')
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

 cy.log('END  check Sending Application For 20CorporateDiscount_withEmptyFirstName');    
    }

    checkSendingApplicationFor20CorporateDiscount_withEmptyLastName(){
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});

        cy.log('Start  check Sending Application For 20CorporateDiscount_withEmptyLastName');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
      //  BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your last name.');
          })

        cy.log('END  check Sending Application For 20CorporateDiscount_withEmptyLastName');
    }

    checkSendingApplicationFor20CorporateDiscount_withEmpty_FieldCompany(){
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});

        cy.log('Start  check Sending Application For 20CorporateDiscount_withEmpty_Company');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
      //  BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your company name.');
          })

        cy.log('END  check Sending Application For 20CorporateDiscount_withEmpty_Company');
    }

    checkSendingApplicationFor20CorporateDiscount_withEmpty_FieldPhone(){

        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});

        cy.log('Start  check Sending Application For 20CorporateDiscount_withFieldPhone');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
     //   BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your phone number.');
          })

          BloomexCorporateAccount_PO.getFieldPhone().type('testtest');
          
          cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your phone number.');
          })


        cy.log('END  check Sending Application For 20CorporateDiscount_withFieldPhone');
    }

    checkSendingApplicationFor20CorporateDiscount_withEmpty_FieldCity(){
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});

        cy.log('Start  check Sending Application For 20CorporateDiscount_withFieldCity');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
     //   BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your city.');
          })

    
        cy.log('END  check Sending Application For 20CorporateDiscount_withFieldCity');
    }

     checkSendingApplicationFor20CorporateDiscount_withEmpty_FieldEmail(){
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});
        cy.log('Start  check Sending Application For 20CorporateDiscount_withFieldEmail');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
     //   BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
        BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your email address.');
          })

          BloomexCorporateAccount_PO.getFieldEmail().clear().type('autotestscypressgmail.com');

          cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your email address.');
          })

        cy.log('END  check Sending Application For 20CorporateDiscount_withFieldEmail');
    }

    checkSendingApplicationFor20CorporateDiscount_withEmpty_FieldPassword(){
        HomePage_PO.getButtonCorporate_ApplyForCorporateDiscount().click({force: true});
        cy.log('Start  check Sending Application For 20CorporateDiscount_withFieldPassword');

        BloomexCorporateAccount_PO.getFieldFirstName().type('Test-Auto-FistName');
        BloomexCorporateAccount_PO.getFieldLastName().type('Test-Auto-LasName'); 
        BloomexCorporateAccount_PO.getFieldTitleName().type('Test-Title'); 
        BloomexCorporateAccount_PO.getFieldCompany().type('Test-Company');
        BloomexCorporateAccount_PO.getFieldPhone().type('0000000000');
        BloomexCorporateAccount_PO.getFieldCity().type('Test-City');
        BloomexCorporateAccount_PO.getFieldState().select('Yukon');
        BloomexCorporateAccount_PO.getFieldEmail().type('autotestscypress@gmail.com');
     //   BloomexCorporateAccount_PO.getFieldPassword().type('Auto@1234');
        BloomexCorporateAccount_PO.getButtonSendApplication().click({force: true});

        cy.on('window:alert', (text) => {
            expect(text).to.equal('Please enter your password.');
          })

        cy.log('END  check Sending Application For 20CorporateDiscount_withFieldPassword');
    }



    


}

export default new CorporateAccount;