import Checkout from '../frontTests/testBloomexCA/testBloomexCA-ENG/steps-ENG/Checkout.steps'
import CheckoutFR from '../frontTests/testBloomexCA/testBloomexCA-FR/steps-FR/Checkout.stepsFR'

let password = 'Auto@4321'
let randomEmail = Math.random().toString(36).substring(2, 8) + Math.floor(Math.random() * 1000);
let email = 'autogeneratedemail' + randomEmail + '@gmail.com'




class AuthorizationCreeds {


    registerLogin() {
        cy.log('Start registration')
            Checkout.Register({
            registerEmail: email,
            registerPassword: password,
            registerFirstname: "QAResgisteredUser",
            registerPhone: "6474494173"
        })
        cy.log('End registration')
    }

    login_autotestscypress() {
        cy.log('Start login')
        Checkout.Authorization({ loginEmail: "autotestscypress@gmail.com", loginPassword: password });
        cy.log('End login')

        
    }


//FR
    registerLoginFR() {
        cy.log('Start registration')
        CheckoutFR.RegisterFR({
            registerEmail: email,
            registerPassword: password,
            registerFirstname: "QAResgisteredUser",
            registerPhone: "6474494173"
        })
        cy.log('End registration')
    }

    login_autotestscypressFR() {
        cy.log('Start login')
        CheckoutFR.AuthorizationFR({ loginEmail: "autotestscypress@gmail.com", loginPassword: password });
        cy.log('End login')
    }

    
}

export default new AuthorizationCreeds;
